# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: brumigue <brumigue@student.42barcelon      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/18 00:25:30 by brumigue          #+#    #+#              #
#    Updated: 2024/06/18 01:15:11 by brumigue         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME = ft_display_file
FILES = display_file.c

.PHONY: all clean fclean

all:
	    @gcc -Wall -Wextra -Werror -o $(NAME) $(FILES)

clean:
	    @rm -f *.o

fclean: clean
	    @rm -f $(NAME)
